# Generated by Django 4.2.6 on 2024-03-10 11:47

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('posts', '0002_hashtag_post_tags'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='like_users',
            field=models.ManyToManyField(blank=True, related_name='Like_post', to=settings.AUTH_USER_MODEL, verbose_name='좋아요 누른 Post 목록'),
        ),
    ]
