apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: claim-log-1
spec:
  resources:
    requests:
      storage: 50Mi
  volumeMode: Filesystem
  accessModes:
  # pv 와 pvc의 accesMode가 맞지 않으면 pvc 는 pending
    - ReadWriteOnce
