apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: rs-nginx
spec:
  # modify replicas according to your case
  replicas: 3
  selector:
    matchLabels:
      tier: rs-nginx
  template:
    metadata:
      labels:
        tier: rs-nginx
    spec:
      containers:
      - name: rs-nginx
        image: nginx
