CREATE TABLE ANIMAL_INS(
    ANIMAL_ID VARCHAR(N) NOT NULL, 
    ANIMAL_TYPE VARCHAR(N) NOT NULL, 
    DATETIME DATETIME NOT NULL, 
    INTAKE_CONDITION VARCHAR(N) NOT NULL, 
    NAME VARCHAR(N) NULL, 
    SEX_UPON_INTAKE VARCHAR(N) NOT NULL
);

INSERT INTO ANIMAL_INS
VALUES(
    ?,
    ?,
    ?,
    ?,
    ?,
    ?
);
