/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/10.0.23
 * Generated at: 2022-09-29 14:31:26 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.msearch;

import jakarta.servlet.*;
import jakarta.servlet.http.*;
import jakarta.servlet.jsp.*;
import java.sql.DriverManager;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;

public final class m_005fsearch_005flist6_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final jakarta.servlet.jsp.JspFactory _jspxFactory =
          jakarta.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(2);
    _jspx_dependants.put("/msearch/m_search_form.jsp", Long.valueOf(1664461603864L));
    _jspx_dependants.put("/minsert/m_insert_form2.jsp", Long.valueOf(1664461603852L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("jakarta.servlet");
    _jspx_imports_packages.add("jakarta.servlet.http");
    _jspx_imports_packages.add("jakarta.servlet.jsp");
    _jspx_imports_classes = new java.util.HashSet<>();
    _jspx_imports_classes.add("java.sql.SQLException");
    _jspx_imports_classes.add("java.sql.Connection");
    _jspx_imports_classes.add("java.sql.ResultSet");
    _jspx_imports_classes.add("java.sql.PreparedStatement");
    _jspx_imports_classes.add("java.sql.DriverManager");
  }

  private volatile jakarta.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public jakarta.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final jakarta.servlet.http.HttpServletRequest request, final jakarta.servlet.http.HttpServletResponse response)
      throws java.io.IOException, jakarta.servlet.ServletException {

    if (!jakarta.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
        return;
      }
    }

    final jakarta.servlet.jsp.PageContext pageContext;
    jakarta.servlet.http.HttpSession session = null;
    final jakarta.servlet.ServletContext application;
    final jakarta.servlet.ServletConfig config;
    jakarta.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    jakarta.servlet.jsp.JspWriter _jspx_out = null;
    jakarta.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=EUC-KR");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<!DOCTYPE html PUBLIC \"-//W3C//DTD HTML 4.01 Transitional//EN\" \"http://www.w3.org/TR/html4/loose.dtd\">\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html PUBLIC \"-//W3C//DTD HTML 4.01 Transitional//EN\" \"http://www.w3.org/TR/html4/loose.dtd\">\r\n");
      out.print( request.getRequestURI() );
      out.write(" <br>\r\n");
      out.write("<form action=\"");
      out.print( request.getContextPath() );
      out.write("/minsert/m_insert_action.jsp\" method=\"post\">\r\n");
      out.write("<table border=\"1\">\r\n");
      out.write("<tr>\r\n");
      out.write("	<td>아이디</td>\r\n");
      out.write("	<td><input type=\"text\" name=\"m_id\" size=\"20\"></td>\r\n");
      out.write("<tr>\r\n");
      out.write("<tr>\r\n");
      out.write("	<td>암호</td>\r\n");
      out.write("	<td><input type=\"text\" name=\"m_pw\" size=\"20\"></td>\r\n");
      out.write("<tr>\r\n");
      out.write("<tr>\r\n");
      out.write("	<td>권한</td>\r\n");
      out.write("	<td><input type=\"text\" name=\"m_level\" size=\"20\"></td>\r\n");
      out.write("<tr>\r\n");
      out.write("<tr>\r\n");
      out.write("	<td>이름</td>\r\n");
      out.write("	<td><input type=\"text\" name=\"m_name\" size=\"20\"></td>\r\n");
      out.write("<tr>\r\n");
      out.write("<tr>\r\n");
      out.write("	<td>이메일</td>\r\n");
      out.write("	<td><input type=\"text\" name=\"m_email\" size=\"20\"></td>\r\n");
      out.write("<tr>\r\n");
      out.write("<tr>\r\n");
      out.write("	<td colspan=\"4\"><input type=\"submit\" value=\"회원가입버튼\"></td>\r\n");
      out.write("</tr>\r\n");
      out.write("</table>\r\n");
      out.write("</form>");
      out.write("<br/>\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html PUBLIC \"-//W3C//DTD HTML 4.01 Transitional//EN\" \"http://www.w3.org/TR/html4/loose.dtd\">\r\n");
      out.write("\r\n");
      out.write("<form action=\"");
      out.print(request.getContextPath());
      out.write("/msearch/m_search_list.jsp\" method=\"post\">\r\n");
      out.write("<select name=\"sk\">\r\n");
      out.write("    <option value=\"m_id\">아이디</option>\r\n");
      out.write("    <option value=\"m_level\">권한</option>\r\n");
      out.write("    <option value=\"m_name\">이름</option>\r\n");
      out.write("    <option value=\"m_email\">이메일</option>\r\n");
      out.write("</select>\r\n");
      out.write("<input type=\"text\" name=\"sv\">\r\n");
      out.write("<input type=\"submit\" value=\"검색버튼\">\r\n");
      out.write("</form>\r\n");
      out.write("\r\n");
      out.write("회원 리스트 <br>\r\n");
      out.write("<table width=\"100%\" border=\"1\">\r\n");
      out.write("<tr>\r\n");
      out.write("	<td>아이디</td><td>비번</td><td>권한</td><td>이름</td><td>이메일</td><td>수정</td><td>삭제</td>\r\n");
      out.write("</tr>\r\n");

request.setCharacterEncoding("euc-kr");	//post한글처리
//search key 와 search value 의미 변수명
String sk = request.getParameter("sk");
String sv = request.getParameter("sv");
System.out.println(sk + "<- sk ");
System.out.println(sv + "<- sv ");
Connection conn = null;
PreparedStatement pstmt = null;
ResultSet rs = null;
Class.forName("com.mysql.jdbc.Driver");
String selectQuery="SELECT * FROM tb_member";
try{
	String jdbcDriver = "jdbc:mysql://localhost:3306/dev00db?" +
			"useUnicode=true&characterEncoding=euckr";
	String dbUser = "dev00id";
	String dbPass = "dev00pw";
	conn = DriverManager.getConnection(jdbcDriver, dbUser, dbPass);
//02단계 :DB연결(Connection)끝
	System.out.println(conn + "<-- conn m_search_form.jsp");
	if((sk == null && sv == null) || (sk != null && sv.equals(""))){
		pstmt = conn.prepareStatement(selectQuery);		
	}else{
		pstmt = conn.prepareStatement(selectQuery+" WHERE "+sk+"=?");
		pstmt.setString(1, sv);
	}
	out.println(pstmt + "<-- pstmt 최종 쿼리 확인");
	rs = pstmt.executeQuery();
	System.out.println(rs + "<-- rs m_search_form.jsp");
	//System.out.println(rs.next() + "<-- rs.next() m_search_form.jsp");
	while(rs.next()){
		System.out.println("while 반복 횟수");
		//System.out.println(rs.getString("m_id") + "<- m_id 컬럼에 담겨있는 값");	
		//화면에 출력할 위치

      out.write("		\r\n");
      out.write("		<tr>\r\n");
      out.write("			<td>");
      out.print( rs.getString("m_id"));
      out.write("</td>\r\n");
      out.write("			<td>");
      out.print( rs.getString("m_pw"));
      out.write("</td>\r\n");
      out.write("			<td>");
      out.print( rs.getString("m_level"));
      out.write("</td>\r\n");
      out.write("			<td>");
      out.print( rs.getString("m_name"));
      out.write("</td>\r\n");
      out.write("			<td>");
      out.print( rs.getString("m_email"));
      out.write("</td>\r\n");
      out.write("			<td>\r\n");
      out.write("<a href=\"");
      out.print( request.getContextPath() );
      out.write("/mupdate/m_update_form.jsp?send_id=");
      out.print( rs.getString("m_id"));
      out.write("\">수정버튼</a>			\r\n");
      out.write("			</td>\r\n");
      out.write("			<td>\r\n");
      out.write("<a href=\"");
      out.print( request.getContextPath() );
      out.write("/mdelete/m_delete_action.jsp?send_id=");
      out.print( rs.getString("m_id"));
      out.write("\">삭제버튼</a>			\r\n");
      out.write("			</td>\r\n");
      out.write("		</tr>		\r\n");

	}

} catch(SQLException ex) {
	out.println(ex.getMessage());
	ex.printStackTrace();
} finally {
	// 6. 사용한 Statement 종료
	if (rs != null) try { rs.close(); } catch(SQLException ex) {}
	if (pstmt != null) try { pstmt.close(); } catch(SQLException ex) {}
	
	// 7. 커넥션 종료
	if (conn != null) try { conn.close(); } catch(SQLException ex) {}
}


      out.write("\r\n");
      out.write("</table>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof jakarta.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
