/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/10.0.23
 * Generated at: 2022-11-18 12:28:33 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.msearch;

import jakarta.servlet.*;
import jakarta.servlet.http.*;
import jakarta.servlet.jsp.*;
import kr.or.ksmart.dao.Mdao;
import java.util.ArrayList;
import kr.or.ksmart.dto.Member;

public final class m_005fsearch_005flist_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final jakarta.servlet.jsp.JspFactory _jspxFactory =
          jakarta.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(4);
    _jspx_dependants.put("/msearch/m_search_form.jsp", Long.valueOf(1668772843584L));
    _jspx_dependants.put("/module/hadan.jsp", Long.valueOf(1668772843581L));
    _jspx_dependants.put("/module/left.jsp", Long.valueOf(1668772843575L));
    _jspx_dependants.put("/module/top.jsp", Long.valueOf(1668772843616L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("jakarta.servlet");
    _jspx_imports_packages.add("jakarta.servlet.http");
    _jspx_imports_packages.add("jakarta.servlet.jsp");
    _jspx_imports_classes = new java.util.HashSet<>();
    _jspx_imports_classes.add("kr.or.ksmart.dao.Mdao");
    _jspx_imports_classes.add("kr.or.ksmart.dto.Member");
    _jspx_imports_classes.add("java.util.ArrayList");
  }

  private volatile jakarta.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public jakarta.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final jakarta.servlet.http.HttpServletRequest request, final jakarta.servlet.http.HttpServletResponse response)
      throws java.io.IOException, jakarta.servlet.ServletException {

    if (!jakarta.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
        return;
      }
    }

    final jakarta.servlet.jsp.PageContext pageContext;
    jakarta.servlet.http.HttpSession session = null;
    final jakarta.servlet.ServletContext application;
    final jakarta.servlet.ServletConfig config;
    jakarta.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    jakarta.servlet.jsp.JspWriter _jspx_out = null;
    jakarta.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=EUC-KR");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<!DOCTYPE html PUBLIC \"-//W3C//DTD HTML 4.01 Transitional//EN\" \"http://www.w3.org/TR/html4/loose.dtd\">\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta http-equiv=\"Content-Type\" content=\"text/html; charset=EUC-KR\">\r\n");
      out.write("<title>Insert title here</title>\r\n");
      out.write("<!-- <link rel=\"stylesheet\" type=\"text/css\" href=\"/layoutMG/css/main.css\" /> -->\r\n");
      out.write("<link rel=\"stylesheet\" type=\"text/css\" href=\"");
      out.print( request.getContextPath() );
      out.write("/css/main2.css\" />\r\n");
      out.write("</head>\r\n");
      out.write("\r\n");
      out.write("<body>\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html PUBLIC \"-//W3C//DTD HTML 4.01 Transitional//EN\" \"http://www.w3.org/TR/html4/loose.dtd\">\r\n");

String S_ID = (String)session.getAttribute("S_ID");
String S_NAME = (String)session.getAttribute("S_NAME");
String S_LEVEL = (String)session.getAttribute("S_LEVEL");
System.out.println(S_ID + "<- S_ID ");
System.out.println(S_NAME + "<- S_NAME ");
System.out.println(S_LEVEL + "<- S_LEVEL ");


      out.write("\r\n");
      out.write("   <!-- Begin Wrapper -->\r\n");
      out.write("   <div id=\"wrapper\">\r\n");
      out.write("   \r\n");
      out.write("         <!-- Begin Header -->\r\n");
      out.write("         <div id=\"header\">\r\n");
      out.write("/module/top.jsp		<br/>		 \r\n");
      out.write("		       상단메뉴	<br/>\r\n");

if(S_LEVEL == null){

      out.write("\r\n");
      out.write("<!-- 1-1 로그인 전 화면 시작 -->\r\n");
      out.write("<a href=\"");
      out.print( request.getContextPath() );
      out.write("/minsert/m_insert_form.jsp\">01회원가입</a><br/><br/>\r\n");
      out.write("<form action=\"");
      out.print( request.getContextPath() );
      out.write("/login/login_action.jsp\" method=\"post\">\r\n");
      out.write("id : <input type=\"text\" name=\"id\">\r\n");
      out.write("pw : <input type=\"password\" name=\"pw\">\r\n");
      out.write("<input type=\"submit\" value=\"로그인버튼\">\r\n");
      out.write("</form>\r\n");
      out.write("<!-- 1-1 로그인 전 화면 끝 -->\r\n");

}else{ 
	if(S_LEVEL.equals("구매자")){

      out.write("\r\n");
      out.write("<a href=\"");
      out.print( request.getContextPath() );
      out.write("/minsert/m_insert_form.jsp\">01회원가입</a>\r\n");
      out.write("<a href=\"#\">04상품검색</a>	<br/><br/>\r\n");

	}else if(S_LEVEL.equals("판매자")){

      out.write("\r\n");
      out.write("<a href=\"");
      out.print( request.getContextPath() );
      out.write("/minsert/m_insert_form.jsp\">01회원가입</a>\r\n");
      out.write("<a href=\"");
      out.print( request.getContextPath() );
      out.write("/goods/goods_insert_form.jsp\">03상품등록</a>\r\n");
      out.write("<a href=\"");
      out.print( request.getContextPath() );
      out.write("/mgsearch/mg_search_list1.jsp\">04회원과상품join검색1(날짜)</a>	<br/><br/>\r\n");

	}else if(S_LEVEL.equals("관리자")){

      out.write("\r\n");
      out.write("<a href=\"");
      out.print( request.getContextPath() );
      out.write("/minsert/m_insert_form.jsp\">01회원가입</a>\r\n");
      out.write("<a href=\"");
      out.print( request.getContextPath() );
      out.write("/msearch/m_search_list.jsp\">02회원검색</a>\r\n");
      out.write("<a href=\"");
      out.print( request.getContextPath() );
      out.write("/goods/goods_insert_form.jsp\">03상품등록</a>\r\n");
      out.write("<a href=\"");
      out.print( request.getContextPath() );
      out.write("/mgsearch/mg_search_list1.jsp\">04회원과상품join검색1(날짜)</a>	<br/><br/>\r\n");

	}

      out.write("\r\n");
      out.write("<!-- 1-2 로그인 후 화면 시작 -->\r\n");
      out.print( S_NAME );
      out.write(' ');
      out.write('님');
      out.write(' ');
      out.print( S_LEVEL );
      out.write(" 권한으로 로그인 중\r\n");
      out.write("<a href=\"");
      out.print( request.getContextPath() );
      out.write("/login/logout.jsp\">로그아웃</a>\r\n");
      out.write("<!-- 1-2 로그인 후 화면 끝 -->\r\n");

}

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("	       		 \r\n");
      out.write("			   \r\n");
      out.write("		 </div>\r\n");
      out.write("		 <!-- End Header -->");
      out.write('\r');
      out.write('\n');
      out.write("\r\n");
      out.write("<!DOCTYPE html PUBLIC \"-//W3C//DTD HTML 4.01 Transitional//EN\" \"http://www.w3.org/TR/html4/loose.dtd\">\r\n");
      out.write("		 <!-- Begin Left Column -->\r\n");
      out.write("		 <div id=\"leftcolumn\">\r\n");
      out.write("/module/left.jsp		<br/>		 \r\n");
      out.write("		      왼쪽메뉴\r\n");
      out.write("		 \r\n");
      out.write("		 </div>\r\n");
      out.write("		 <!-- End Left Column -->\r\n");
      out.write("		 		 <!-- Begin Right Column -->\r\n");
      out.write("		 <div id=\"rightcolumn\">");
      out.write('\r');
      out.write('\n');
      out.write("\r\n");
      out.write("<!DOCTYPE html PUBLIC \"-//W3C//DTD HTML 4.01 Transitional//EN\" \"http://www.w3.org/TR/html4/loose.dtd\">\r\n");
      out.write("\r\n");
      out.write("<form action=\"");
      out.print(request.getContextPath());
      out.write("/msearch/m_search_list.jsp\" method=\"post\">\r\n");
      out.write("<select name=\"sk\">\r\n");
      out.write("    <option value=\"m_id\">아이디</option>\r\n");
      out.write("    <option value=\"m_level\">권한</option>\r\n");
      out.write("    <option value=\"m_name\">이름</option>\r\n");
      out.write("    <option value=\"m_email\">이메일</option>\r\n");
      out.write("</select>\r\n");
      out.write("<input type=\"text\" name=\"sv\">\r\n");
      out.write("<input type=\"submit\" value=\"검색버튼\">\r\n");
      out.write("</form>\r\n");
      out.write("\r\n");
      out.write("회원 리스트 <br>\r\n");
      out.write("<table width=\"100%\" border=\"1\">\r\n");
      out.write("<tr>\r\n");
      out.write("	<td>아이디</td><td>비번</td><td>권한</td><td>이름</td><td>이메일</td><td>수정</td><td>삭제</td>\r\n");
      out.write("</tr>\r\n");

request.setCharacterEncoding("euc-kr");	//post한글처리
//search key 와 search value 의미 변수명
String sk = request.getParameter("sk");
String sv = request.getParameter("sv");
System.out.println(sk + "<- sk ");
System.out.println(sv + "<- sv ");
Mdao mdao = new Mdao();
ArrayList<Member> alm = mdao.mSearch(sk, sv);
System.out.println(alm + "<- alm m_search_list.jsp");
out.println("검색 결과 회원 수 : "+alm.size() + "<br/><br/>");
for(int i=0;i<alm.size();i++){
	System.out.println(alm.get(i) + "<- alm.get(" + i+ ")" + "m_list.jsp");
	Member m = (Member)alm.get(i);
	/* out.println(m.getM_id() +"<- m.getM_id() <br/>"); */
	/* out.println(alm.get(i).getM_id() + "<- alm.get(" + i+ ").getM_id()" + "m_list.jsp	<br/>"); */

      out.write("\r\n");
      out.write("<tr>\r\n");
      out.write("	<td>");
      out.print( m.getM_id() );
      out.write("</td>\r\n");
      out.write("	<td>");
      out.print( m.getM_pw() );
      out.write("</td>\r\n");
      out.write("	<td>");
      out.print( m.getM_level() );
      out.write("</td>\r\n");
      out.write("	<td>");
      out.print( m.getM_name() );
      out.write("</td>\r\n");
      out.write("	<td>");
      out.print( m.getM_email() );
      out.write("</td>\r\n");
      out.write("	\r\n");
      out.write("	<td>\r\n");
      out.write("	<a href=\"");
      out.print( request.getContextPath() );
      out.write("/mupdate/m_update_form.jsp?send_id=");
      out.print( m.getM_id() );
      out.write("\">수정버튼</a>			\r\n");
      out.write("	</td>\r\n");
      out.write("	<td>\r\n");
      out.write("	<a href=\"");
      out.print( request.getContextPath() );
      out.write("/mdelete/m_delete_action.jsp?send_id=");
      out.print( m.getM_id() );
      out.write("\">삭제버튼</a>			\r\n");
      out.write("	</td>\r\n");
      out.write("</tr>	\r\n");
	
}

      out.write("	\r\n");
      out.write("</table>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html PUBLIC \"-//W3C//DTD HTML 4.01 Transitional//EN\" \"http://www.w3.org/TR/html4/loose.dtd\">\r\n");
      out.write("		 </div>\r\n");
      out.write("		 <!-- End Right Column -->\r\n");
      out.write("		 \r\n");
      out.write("		 <!-- Begin Footer -->\r\n");
      out.write("		 <div id=\"footer\">\r\n");
      out.write("/module/hadan.jsp		<br/>		       \r\n");
      out.write("			  하단메뉴		<br/>\r\n");
      out.write("063-717-1008 ksmart.or.kr 한국스마트정보교육원					  \r\n");
      out.write("			    \r\n");
      out.write("	     </div>\r\n");
      out.write("		 <!-- End Footer -->\r\n");
      out.write("		 \r\n");
      out.write("   </div>\r\n");
      out.write("   <!-- End Wrapper -->");
      out.write("\r\n");
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("</html>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof jakarta.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
